# Generated by Django 5.0.6 on 2024-05-31 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=255)),
                ('deliver', models.CharField(max_length=255)),
                ('image_1', models.ImageField(default='default_post_wndtrr', upload_to='images/')),
                ('image_2', models.ImageField(upload_to='images/')),
                ('image_3', models.ImageField(upload_to='images/')),
                ('image_4', models.ImageField(upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
