# Generated by Django 5.0.6 on 2024-07-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('leads', 'Leads'), ('collars', 'Collars'), ('lead_collar_sets', 'Lead & Collar Sets'), ('harnesses', 'Harnesses'), ('harness_lead_sets', 'Harness & Lead Sets'), ('dog_food', 'Dog Food'), ('treats', 'Treats'), ('toys', 'Toys'), ('clothing', 'Clothing'), ('crates', 'Crates'), ('dog_beds', 'Dog Beds'), ('dog_pens', 'Dog Pens'), ('dog_gates', 'Dog Gates'), ('dog_carriers', 'Dog Carriers'), ('bowls_feeding_accessories', 'Bowls & Feeding Accessories'), ('training_accessories', 'Training Accessories'), ('dog_grooming', 'Dog Grooming'), ('other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='advert',
            name='deliver',
            field=models.CharField(choices=[('collection_only', 'Collection Only'), ('post_only', 'Post Only'), ('either', 'Either Collection or Post')], max_length=255),
        ),
        migrations.AlterField(
            model_name='advert',
            name='location',
            field=models.CharField(choices=[('location1', 'Location 1'), ('location2', 'Location 2'), ('location3', 'Location 3')], max_length=255),
        ),
    ]
