# Generated by Django 5.0.6 on 2024-07-08 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_location_alter_advert_category_alter_advert_deliver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.location'),
        ),
    ]
