# Generated by Django 5.0.6 on 2024-07-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_alter_advert_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
