# Generated by Django 5.0.6 on 2024-07-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_remove_advert_location_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='location',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
