# Generated by Django 5.0.6 on 2024-07-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_advert_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='advert',
            name='deliver',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='advert',
            name='image_2',
            field=models.ImageField(default='default_post_wndtrr', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='image_3',
            field=models.ImageField(default='default_post_wndtrr', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='image_4',
            field=models.ImageField(default='default_post_wndtrr', upload_to='images/'),
        ),
    ]
