# Generated by Django 5.0.6 on 2024-07-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0006_alter_advert_category_alter_advert_deliver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
