from rest_framework import generics, permissions, filters
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.decorators import permission_classes
from preloved.permissions import IsOwnerOrReadOnly
from .models import Advert
from .serializers import CategorySerializer, LocationSerializer, DeliverSerializer, AdvertSerializer
from django_filters.rest_framework import DjangoFilterBackend
from .filters import AdvertFilter


class AdvertList(generics.ListCreateAPIView):
    """
    Create and list adverts 
    """

    serializer_class = AdvertSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    queryset = Advert.objects.all()
    filter_backends = [
        DjangoFilterBackend,
        filters.SearchFilter,
    ]
    filterset_class = AdvertFilter
    search_fields = [
        "title",
        "description",
    ]

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

    
class AdvertDetail(generics.RetrieveUpdateDestroyAPIView):
    """
    Retrieve, edit and delete an advert
    """

    permission_classes = [IsOwnerOrReadOnly]
    serializer_class = AdvertSerializer   
    queryset = Advert.objects.all()


@api_view(["GET"])
@permission_classes([permissions.AllowAny])
def category_choices(request):
    choices = [
        {"value": "leads", "label": "Leads"},
        {"value": "collars", "label": "Collars"},
        {"value": "lead_collar_sets", "label": "Lead & Collar Sets"},
        {"value": "harnesses", "label": "Harnesses"},
        {"value": "harness_lead_sets", "label": "Harness & Lead Sets"},
        {"value": "dog_food", "label": "Dog Food"},
        {"value": "treats", "label": "Treats"},
        {"value": "toys", "label": "Toys"},
        {"value": "clothing", "label": "Clothing"},
        {"value": "crates", "label": "Crates"},
        {"value": "dog_beds", "label": "Dog Beds"},
        {"value": "dog_pens", "label": "Dog Pens"},
        {"value": "dog_gates", "label": "Dog Gates"},
        {"value": "dog_carriers", "label": "Dog Carriers"},
        {"value": "bowls_feeding_accessories", "label": "Bowls & Feeding Accessories"},
        {"value": "training_accessories", "label": "Training Accessories"},
        {"value": "dog_grooming", "label": "Dog Grooming"},
        {"value": "other", "label": "Other"},
    ]

    serializer = CategorySerializer(choices, many=True)
    return Response(serializer.data)


@api_view(["GET"])
@permission_classes([permissions.AllowAny])
def location_choices(request):
    choices = [
        {"value": "aberdeen", "label": "Aberdeen"},
        {"value": "abingdon", "label": "Abingdon"},
        {"value": "acton", "label": "Acton"},
        {"value": "airdrie", "label": "Airdrie"},
        {"value": "aldridge", "label": "Aldridge"},
        {"value": "altrincham", "label": "Altrincham"},
        {"value": "andover", "label": "Andover"},
        {"value": "arnold", "label": "Arnold"},
        {"value": "ashington", "label": "Ashington"},
        {"value": "ashton", "label": "Ashton"},
        {"value": "aylesbury", "label": "Aylesbury"},
        {"value": "bangor", "label": "Bangor"},
        {"value": "barking", "label": "Barking"},
        {"value": "barnet", "label": "Barnet"},
        {"value": "barrow_in_furness", "label": "Barrow in Furness"},
        {"value": "basildon", "label": "Basildon"},
        {"value": "basingstoke", "label": "Basingstoke"},
        {"value": "bath", "label": "Bath"},
        {"value": "batley", "label": "Batley"},
        {"value": "bebington", "label": "Bebington"},
        {"value": "beckenham", "label": "Beckenham"},
        {"value": "beeston", "label": "Beeston"},
        {"value": "belfast", "label": "Belfast"},       
        {"value": "bexleyheath", "label": "Bexleyheath"},
        {"value": "bicester", "label": "Bicester"},
        {"value": "billingham", "label": "Billingham"},
        {"value": "bilston", "label": "Bilston"},
        {"value": "birmingham", "label": "Birmingham"},
        {"value": "bishop_auckland", "label": "Bishop Auckland"},
        {"value": "bishops_stortford", "label": "Bishops Stortford"},
        {"value": "Blackburn", "label": "Blackburn"},
        {"value": "blackpool", "label": "Blackpool"},
        {"value": "bletchley", "label": "Bletchley"},
        {"value": "bloxwich", "label": "Bloxwich"},
        {"value": "blyth", "label": "Blyth"},
        {"value": "bootle", "label": "Bootle"},
        {"value": "borehamwood", "label": "Borehamwood"},
        {"value": "boston", "label": "Boston"},
        {"value": "bournemouth", "label": "Bournemouth"},
        {"value": "bournville", "label": "Bournville"},
        {"value": "bradford", "label": "Bradford"},
        {"value": "braintree", "label": "Braintree"},
        {"value": "bridgwater", "label": "Bridgwater"},
        {"value": "bridlington", "label": "Bridlington"},
        {"value": "bristol", "label": "Bristol"},
        {"value": "brixton", "label": "Brixton"},
        {"value": "broadstairs", "label": "Broadstairs"},
        {"value": "bromsgrove", "label": "Bromsgrove"},
        {"value": "bulwell", "label": "Bulwell"},
        {"value": "Burnley", "label": "Burnley"},
        {"value": "burton_upon_trent", "label": "Burton upon Trent"},
        {"value": "caerphilly", "label": "Caerphilly"},
        {"value": "Cambridge", "label": "Cambridge"},
        {"value": "carlisle", "label": "Carlisle"},
        {"value": "carshalton", "label": "Carshalton"},
        {"value": "castleford", "label": "Castleford"},
        {"value": "catford", "label": "Catford"},
        {"value": "chatham", "label": "Chatham"},
        {"value": "cheadle_hulme", "label": "Cheadle Hulme"},
        {"value": "chelmsford", "label": "Chelmsford"},
        {"value": "cheshunt", "label": "Cheshunt"},
        {"value": "chester", "label": "Chester"},
        {"value": "chichester", "label": "Chichester"},
        {"value": "chingford", "label": "Chingford"},
        {"value": "chorley", "label": "Chorley"},
        {"value": "cleethorpes", "label": "Cleethorpes"},
        {"value": "coalville", "label": "Coalville"},
        {"value": "colchester", "label": "Colchester"},
        {"value": "consett", "label": "Consett"},
        {"value": "coulsdon", "label": "Coulsdon"},
        {"value": "coventry", "label": "Coventry"},
        {"value": "cramlington", "label": "Cramlington"},
        {"value": "crewe", "label": "Crewe"},
        {"value": "crosby", "label": "Crosby"},
        {"value": "croydon", "label": "Croydon"},
        {"value": "cumbernauld", "label": "Cumbernauld"},
        {"value": "darlaston", "label": "Darlaston"},
        {"value": "darlington", "label": "Darlington"},
        {"value": "darwen", "label": "Darwen"},
        {"value": "deal", "label": "Deal"},
        {"value": "denton", "label": "Denton"},
        {"value": "derby", "label": "Derby"},
        {"value": "dewsbury", "label": "Dewsbury"},
        {"value": "didcot", "label": "Didcot"},
        {"value": "dover", "label": "Dover"},
        {"value": "droitwich", "label": "Droitwich"},
        {"value": "dudley", "label": "Dudley"},
        {"value": "dunfermline", "label": "Dunfermline"},
        {"value": "dunstable", "label": "Dunstable"},
        {"value": "ealing", "label": "Ealing"},
        {"value": "earley", "label": "Earley"},
        {"value": "east_ham", "label": "East Ham"},
        {"value": "east_kilbride", "label": "East Kilbride"},
        {"value": "ecclesfield", "label": "Ecclesfield"},
        {"value": "edgware", "label": "Edgware"},
        {"value": "edmonton", "label": "Edmonton"},
        {"value": "ellesmere_port", "label": "Ellesmere Port"},
        {"value": "eltham", "label": "Eltham"},
        {"value": "falkirk", "label": "Falkirk"},
        {"value": "fareham", "label": "Fareham"},
        {"value": "farnworth", "label": "Farnworth"},
        {"value": "feltham", "label": "Feltham"},
        {"value": "finchley", "label": "Finchley"},
        {"value": "fleet", "label": "Fleet"},
        {"value": "folkestone", "label": "Folkestone"},
        {"value": "frome", "label": "Frome"},
        {"value": "fulham", "label": "Fulham"},
        {"value": "gateshead", "label": "Gateshead"},
        {"value": "gloucester", "label": "Gloucester"},
        {"value": "grantham", "label": "Grantham"},
        {"value": "grays", "label": "Grays"},
        {"value": "great_yarmouth", "label": "Great Yarmouth"},
        {"value": "greenford", "label": "Greenford"},
        {"value": "guiseley", "label": "Guiseley"},
        {"value": "hammersmith", "label": "Hammersmith"},
        {"value": "hampstead", "label": "Hampstead"},
        {"value": "hanwell", "label": "Hanwell"},
        {"value": "harrogate", "label": "Harrogate"},
        {"value": "harrow", "label": "Harrow"},
        {"value": "hartlepool", "label": "Hartlepool"},
        {"value": "hastings", "label": "Hastings"},
        {"value": "hayes", "label": "Hayes"},
        {"value": "hemel_hempstead", "label": "Hemel Hempstead"},
        {"value": "herne_bay", "label": "Herne Bay"},
        {"value": "highbury", "label": "Highbury"},
        {"value": "high_wycombe", "label": "High Wycombe"},
        {"value": "hindley", "label": "Hindley"},
        {"value": "hitchin", "label": "Hitchin"},
        {"value": "hornchurch", "label": "Hornchurch"},
        {"value": "hounslow", "label": "Hounslow"},
        {"value": "hove", "label": "Hove"},
        {"value": "huyton", "label": "Huyton"},
        {"value": "ilford", "label": "Ilford"},
        {"value": "ilkeston", "label": "Ilkeston"},
        {"value": "islington", "label": "Islington"},
        {"value": "kendal", "label": "Kendal"},
        {"value": "kensington", "label": "Kensington"},
        {"value": "kenton", "label": "Kenton"},
        {"value": "kettering", "label": "Kettering"},
        {"value": "kingswood", "label": "Kingswood"},
        {"value": "kirkby", "label": "Kirkby"},
        {"value": "laindon", "label": "Laindon"},
        {"value": "lancaster", "label": "Lancaster"},
        {"value": "leicester", "label": "Leicester"},
        {"value": "leighton_buzzard", "label": "Leighton Buzzard"},
        {"value": "leith", "label": "Leith"},
        {"value": "letchworth", "label": "Letchworth"},
        {"value": "littlehampton", "label": "Littlehampton"},
        {"value": "liverpool", "label": "Liverpool"},
        {"value": "llanelli", "label": "Llanelli"},
        {"value": "london", "label": "London"},
        {"value": "longbridge", "label": "Longbridge"},
        {"value": "longton", "label": "Longton"},
        {"value": "loughborough", "label": "Loughborough"},
        {"value": "lowestoft", "label": "Lowestoft"},
        {"value": "luton", "label": "Luton"},
        {"value": "macclesfield", "label": "Macclesfield"},
        {"value": "maidstone", "label": "Maidstone"},
        {"value": "manchester", "label": "Manchester"},
        {"value": "melton_mowbray", "label": "Melton Mowbray"},
        {"value": "merthyr_tydfil", "label": "Merthyr Tydfil"},
        {"value": "middleton", "label": "Middleton"},
        {"value": "mitcham", "label": "Mitcham"},
        {"value": "morden", "label": "Morden"},
        {"value": "morley", "label": "Morley"},
        {"value": "neath", "label": "Neath"},
        {"value": "newbury", "label": "Newbury"},
        {"value": "newton_aycliffe", "label": "Newton Aycliffe"},
        {"value": "newtownards", "label": "Newtownards"},
        {"value": "northampton", "label": "Northampton"},
        {"value": "northolt", "label": "Northolt"},
        {"value": "north_shields", "label": "North Shields"},
        {"value": "norwich", "label": "Norwich"},
        {"value": "nottingham", "label": "Nottingham"},
        {"value": "nuneaton", "label": "Nuneaton"},
        {"value": "oxford", "label": "Oxford"},
        {"value": "paignton", "label": "Paignton"},
        {"value": "paisley", "label": "Paisley"},
        {"value": "pinner", "label": "Pinner"},
        {"value": "plymouth", "label": "Plymouth"},
        {"value": "pontypridd", "label": "Pontypridd"},
        {"value": "pont_y_pŵl", "label": "Pont-y-pŵl"},
        {"value": "portsmouth", "label": "Portsmouth"},
        {"value": "prestwich", "label": "Prestwich"},
        {"value": "rainham", "label": "Rainham"},
        {"value": "ramsgate", "label": "Ramsgate"},
        {"value": "rayleigh", "label": "Rayleigh"},
        {"value": "rhyl", "label": "Rhyl"},
        {"value": "rochdale", "label": "Rochdale"},
        {"value": "rochester", "label": "Rochester"},
        {"value": "Romford", "label": "Romford"},
        {"value": "rotherham", "label": "Rotherham"},
        {"value": "rowley_regis", "label": "Rowley Regis"},
        {"value": "royal_leamington_spa", "label": "Royal Leamington Spa"},
        {"value": "royal_tunbridge_wells", "label": "Royal Tunbridge Wells"},
        {"value": "rugby", "label": "Rugby"},
        {"value": "ruislip", "label": "Ruislip"},
        {"value": "rutherglen", "label": "Rutherglen"},
        {"value": "saint_albans", "label": "Saint Albans"},
        {"value": "sale", "label": "Sale"},
        {"value": "salford", "label": "Salford"},
        {"value": "salisbury", "label": "Salisbury"},
        {"value": "scarborough", "label": "Scarborough"},
        {"value": "scunthorpe", "label": "Scunthorpe"},
        {"value": "shenley_brook_end", "label": "Shenley Brook End"},
        {"value": "slough", "label": "Slough"},
        {"value": "small_heath", "label": "Small Heath"},
        {"value": "solihull", "label": "Solihull"},
        {"value": "southall", "label": "Southall"},
        {"value": "southampton", "label": "Southampton"},
        {"value": "south_shields", "label": "South Shields"},
        {"value": "spalding", "label": "Spalding"},
        {"value": "stevenage", "label": "Stevenage"},
        {"value": "stockport", "label": "Stockport"},
        {"value": "stourbridge", "label": "Stourbridge"},
        {"value": "stratford", "label": "Stratford"},
        {"value": "streatham", "label": "Streatham"},
        {"value": "stretford", "label": "Stretford"},
        {"value": "strood", "label": "Strood"},
        {"value": "surbiton", "label": "Surbiton"},
        {"value": "sutton", "label": "Sutton"},
        {"value": "sutton_in_ashfield", "label": "Sutton in Ashfield"},
        {"value": "taunton", "label": "Taunton"},
        {"value": "thornton_heath", "label": "Thornton Heath"},
        {"value": "tottenham", "label": "Tottenham"},
        {"value": "trowbridge", "label": "Trowbridge"},
        {"value": "twickenham", "label": "Twickenham"},   
        {"value": "upminster", "label": "Upminster"},
        {"value": "urmston", "label": "Urmston"},
        {"value": "uxbridge", "label": "Uxbridge"},
        {"value": "walkden", "label": "Walkden"},
        {"value": "walsall", "label": "Walsall"},
        {"value": "walthamstow", "label": "Walthamstow"},
        {"value": "walton_upon_thames", "label": "Walton upon Thames"},
        {"value": "warrington", "label": "Warrington"},
        {"value": "waterlooville", "label": "Waterlooville"},
        {"value": "watford", "label": "Watford"},
        {"value": "welling", "label": "Welling"},
        {"value": "wellingborough", "label": "Wellingborough"},
        {"value": "wellington", "label": "Wellington"},
        {"value": "wembley", "label": "Wembley"},
        {"value": "west_bridgford", "label": "West Bridgford"},
        {"value": "west_bromwich", "label": "West Bromwich"},
        {"value": "westhoughton", "label": "Westhoughton"},
        {"value": "westminster", "label": "Westminster"},
        {"value": "weston_super_mare", "label": "Weston-super-Mare"},
        {"value": "wigston_magna", "label": "Wigston Magna"},
        {"value": "wishaw", "label": "Wishaw"},
        {"value": "whitley_bay", "label": "Whitley Bay"},
        {"value": "wickford", "label": "Wickford"},
        {"value": "wolverhampton", "label": "Wolverhampton"},
        {"value": "wood_green", "label": "Wood Green"},
        {"value": "worcester", "label": "Worcester"},
        {"value": "worksop", "label": "Worksop"},
        {"value": "worthing", "label": "Worthing"},
        {"value": "wrexham", "label": "Wrexham"},
        {"value": "yeovil", "label": "Yeovil"},
        {"value": "york", "label": "York"},
    ]

    serializer = LocationSerializer(choices, many=True)
    return Response(serializer.data)

@api_view(["GET"])
@permission_classes([permissions.AllowAny])
def deliver_choices(request):
    choices = [
        {"value": "collection_only", "label": "Collection Only"},
        {"value": "post_only", "label": "Post Only"},
        {"value": "either", "label": "Either Collection or Post"},
    ]

    serializer = DeliverSerializer(choices, many=True)
    return Response(serializer.data)